export const WS_CONNECTION_START:'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS:'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR:'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED:'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_CLOSE:'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE';
export const WS_GET_MESSAGE:'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE:'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_USER_NAME_UPDATE:'WS_USER_NAME_UPDATE' = 'WS_USER_NAME_UPDATE';
export const WS_START_WITH_CUSTOM_URL:'WS_START_WITH_CUSTOM_URL' = 'WS_START_WITH_CUSTOM_URL';




export const wsActions = {
    wsInit: WS_CONNECTION_START,
    wsInitCustom: WS_START_WITH_CUSTOM_URL,
    wsSendMessage: WS_SEND_MESSAGE,
    onOpen: WS_CONNECTION_SUCCESS,
    onClose: WS_CONNECTION_CLOSED,
    wsClose: WS_CONNECTION_CLOSE,
    onError: WS_CONNECTION_ERROR,
    onMessage: WS_GET_MESSAGE
  };

